name: Deploy EC2 Instance

on:
  push:
    branches:
      - vicky
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22

          timeout: 300s
          command_timeout: 30m
          request_pty: true
          script_stop: true

          script: |
            set -ex

            cd ~/marvel/demo-voice-agent
            git pull origin ${{ github.ref_name }}

            docker system prune -af || true

            docker stop livekit-agent || true
            docker rm livekit-agent || true

            docker build -t livekit-voice-agent .

            docker run -d --name livekit-agent --restart unless-stopped \
            -e LIVEKIT_URL="${{ secrets.LIVEKIT_URL }}" \
            -e LIVEKIT_API_KEY="${{ secrets.LIVEKIT_API_KEY }}" \
            -e LIVEKIT_API_SECRET="${{ secrets.LIVEKIT_API_SECRET }}" \
            -e GOOGLE_API_KEY="${{ secrets.GOOGLE_API_KEY }}" \
            livekit-voice-agent 
